name: Development CI

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!staging'

env:
  TARGET_BRANCH: ${{ github.ref_name }}

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    - name: git fetch
      run: |
        git fetch
    - name: show branch
      run: |
        echo ${{ github.ref_name }}